# Generated by Django 4.1.2 on 2022-10-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to="yolo5", verbose_name=""),
        ),
    ]
